[CmdletBinding()]
param()

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

$inputPath = [string]$env:FG_AV1_FINAL_INPUT
$rawOutput = [string]$env:FG_AV1_FINAL_RAW_OUTPUT
$grainTag = [string]$env:FG_AV1_FINAL_TAG
$extension = [string]$env:FG_AV1_FINAL_EXT
$grav1synth = [string]$env:FG_AV1_FINAL_GRAV1SYNTH
$resultPath = [string]$env:FG_AV1_FINAL_RESULT
$sourceAction = [string]$env:FG_AV1_SOURCE_GRAIN_ACTION

if ([string]::IsNullOrWhiteSpace($inputPath) -or
    [string]::IsNullOrWhiteSpace($rawOutput) -or
    [string]::IsNullOrWhiteSpace($grainTag) -or
    [string]::IsNullOrWhiteSpace($extension) -or
    [string]::IsNullOrWhiteSpace($resultPath)) {
    throw 'Missing AV1 filename finalizer environment data.'
}

if (-not (Test-Path -LiteralPath $inputPath -PathType Leaf)) {
    throw "Input file not found: $inputPath"
}
if (-not (Test-Path -LiteralPath $rawOutput -PathType Leaf)) {
    throw "Processed output file not found: $rawOutput"
}

# Studio already inspects the selected AV1.  Use that result when available.
# Standalone BAT usage falls back to one shell-free grav1synth inspect here.
if ($sourceAction -notin @('ADDED','REPLACED')) {
    if ([string]::IsNullOrWhiteSpace($grav1synth) -or -not (Test-Path -LiteralPath $grav1synth -PathType Leaf)) {
        throw "grav1synth not found: $grav1synth"
    }

    $token = [Guid]::NewGuid().ToString('N')
    $inspectTable = Join-Path ([System.IO.Path]::GetTempPath()) ("AV1FG_finalize_$token.txt")
    $inspectStdout = Join-Path ([System.IO.Path]::GetTempPath()) ("AV1FG_finalize_$token.out.log")
    $inspectStderr = Join-Path ([System.IO.Path]::GetTempPath()) ("AV1FG_finalize_$token.err.log")

    try {
        $psi = New-Object System.Diagnostics.ProcessStartInfo
        $psi.FileName = $grav1synth
        $psi.Arguments = 'inspect "' + $inputPath + '" -o "' + $inspectTable + '" -y'
        $psi.UseShellExecute = $false
        $psi.CreateNoWindow = $true
        $psi.RedirectStandardOutput = $true
        $psi.RedirectStandardError = $true

        $proc = New-Object System.Diagnostics.Process
        $proc.StartInfo = $psi
        if (-not $proc.Start()) { throw 'Could not start grav1synth inspect.' }
        $stdoutTask = $proc.StandardOutput.ReadToEndAsync()
        $stderrTask = $proc.StandardError.ReadToEndAsync()
        $proc.WaitForExit()
        $stdoutText = [string]$stdoutTask.Result
        $stderrText = [string]$stderrTask.Result
        $inspectRc = $proc.ExitCode
        $proc.Dispose()

        [System.IO.File]::WriteAllText($inspectStdout, $stdoutText, (New-Object System.Text.UTF8Encoding($false)))
        [System.IO.File]::WriteAllText($inspectStderr, $stderrText, (New-Object System.Text.UTF8Encoding($false)))

        if ($inspectRc -ne 0) {
            throw "grav1synth inspect failed with exit code $inspectRc."
        }

        $grainPresent = $false
        if (Test-Path -LiteralPath $inspectTable -PathType Leaf) {
            $first = [System.IO.File]::ReadLines($inspectTable) | Select-Object -First 1
            if (([string]$first).Trim() -ieq 'filmgrn1') { $grainPresent = $true }
        }
        $sourceAction = if ($grainPresent) { 'REPLACED' } else { 'ADDED' }
    } finally {
        Remove-Item -LiteralPath $inspectTable -Force -ErrorAction SilentlyContinue
        Remove-Item -LiteralPath $inspectStdout -Force -ErrorAction SilentlyContinue
        Remove-Item -LiteralPath $inspectStderr -Force -ErrorAction SilentlyContinue
    }
}

$directory = [System.IO.Path]::GetDirectoryName($inputPath)
$baseName = [System.IO.Path]::GetFileNameWithoutExtension($inputPath)

# Remove the complete trailing AV1FG chain generated by this project.
# Examples:
#   name_AV1FG_Classic35_ADDED -> name
#   name_AV1FG_Classic35_ADDED_AV1FG_Super8_REPLACED -> name
$cleanBase = [System.Text.RegularExpressions.Regex]::Replace(
    $baseName,
    '(?:_AV1FG_.+?_(?:ADDED|REPLACED))+$',
    '',
    [System.Text.RegularExpressions.RegexOptions]::IgnoreCase
)
if ([string]::IsNullOrWhiteSpace($cleanBase)) { $cleanBase = $baseName }

$finalName = $cleanBase + '_AV1FG_' + $grainTag + '_' + $sourceAction + '.' + $extension
$finalPath = Join-Path $directory $finalName

if (-not [string]::Equals($rawOutput, $finalPath, [System.StringComparison]::OrdinalIgnoreCase)) {
    if (Test-Path -LiteralPath $finalPath) {
        throw "Target output already exists: $finalPath"
    }
    [System.IO.File]::Move($rawOutput, $finalPath)
}

# This result file is consumed by CMD TYPE and then captured by the Studio GUI.
# Use the local Windows code page so CMD output and GUI decoding stay aligned.
[System.IO.File]::WriteAllText($resultPath, $finalPath, [System.Text.Encoding]::Default)
exit 0
